src/objects/PlaceTag__c.object
<CustomObject>
    <fields>
        <fullName>Color__c</fullName>
        <inlineHelpText>#RRGGBB</inlineHelpText>
        <label>色</label>
        <length>7</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IconURL__c</fullName>
        <label>アイコンURL</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>場所タグ</label>
    <nameField>
        <label>場所タグ名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PlaceMapControllerTest.cls
@isTest
private class PlaceMapControllerTest {
    static ID newTag(String name, String color, String icon) {
        PlaceTag__c tag = new PlaceTag__c(
            Name = name,
            Color__c = color,
            IconURL__c = icon
        );
        insert tag;
        return tag.Id;
    }

    static testMethod void allTest() {
        ID tagId = newTag('hoge', '#ff00ff', '/test.png');
        PlaceMapController.placeTags();
        PlaceMapController.addPlace('test', 'address', 0, 0, tagId); 
        PlaceMapController.search('test', tagId);
        PlaceMapController.search('test', null);
    }
}