src/objects/Place__c.object
<CustomObject>
    <label>場所</label>
    <nameField>
        <label>場所</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PlaceTag__c.object
<CustomObject>
    <fields>
        <fullName>Color__c</fullName>
        <inlineHelpText>#RRGGBB</inlineHelpText>
        <label>色</label>
        <length>7</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IconURL__c</fullName>
        <label>アイコンURL</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>場所タグ</label>
    <nameField>
        <label>場所タグ名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PlaceTagReference__c.object
<CustomObject>
    <fields>
        <fullName>PlaceTag__c</fullName>
        <label>場所タグ</label>
        <referenceTo>PlaceTag__c</referenceTo>
        <relationshipLabel>場所タグ関連</relationshipLabel>
        <relationshipName>PlaceTags</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Place__c</fullName>
        <label>場所</label>
        <referenceTo>Place__c</referenceTo>
        <relationshipLabel>場所タグ関連</relationshipLabel>
        <relationshipName>PlaceTags</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>場所タグ関連</label>
    <nameField>
        <displayFormat>PTR-{000000}</displayFormat>
        <label>場所タグ関連名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PlaceMapController.cls
global class PlaceMapController {
    @RemoteAction
    global static  List<Place__c> search(String name, String tags) {
        if (tags == null || tags == '') tags = '';
        String soql = 'Select Place__r.Name, Place__r.Location__latitude__s, Place__r.Location__longitude__s From PlaceTagReference__c ' +
            ' Where PlaceTag__c In :tagsList ';
        List<String> tagsList = tags.split(',');
        List<Place__c> places = new List<Place__c>();
        if (name != null && name != '') {
            soql += 'And Place__r.Name like \'%' + String.escapeSingleQuotes(name) + '%\'';
        }
        List<PlaceTagReference__c> tmp = Database.query(soql);
        soql += ' Limit 10000';
        for (PlaceTagReference__c t : tmp) {
            places.add(t.Place__r);
        }
        return places;
    }

    @RemoteAction
    global static List<PlaceTag__c> placeTags() {
        return [Select Name, IconURL__c, Color__c From PlaceTag__c Order By Name];
    }

    @RemoteAction
    global static Place__c addPlace(String name, Decimal lat, Decimal lng, String tags) {
        List<String> tagsList = tags.split(',');
        Place__c place = new Place__c(
            Name = name,
            Location__latitude__s = lat,
            Location__longitude__s = lng
        );
        insert place;

        List< PlaceTagReference__c > placeTagReferences = new List<PlaceTagReference__c>();
        for (String tag : tagsList) {
            placeTagReferences.add(new PlaceTagReference__c(
                Place__c = place.Id,
                PlaceTag__c = tag
            ));
        }
        insert placeTagReferences;

        return place;
    }
}